#!/usr/bin/env python3
"""Generate the engine's Gen 1 static data from the oracle (Showdown, via poke-env),
and audit our hand-coded type chart against it.

Run from the agent env (which has poke-env), e.g. from `agent/`:

    uv run python ../engine/tools/gen_data.py

It does two things:
  1. Prints every cell where our hand-coded Gen 1 type chart disagrees with poke-env's
     (this is the fidelity audit — it reveals exactly where my memory was wrong).
  2. Writes engine/include/cinnabar/gen1_data.hpp with the correct type chart + base
     stats, for the engine to adopt (replacing the hand-coded data) in the next slice.

This is the "generate data from Showdown, don't hand-type it" step from the engine README.
"""

from __future__ import annotations

from pathlib import Path

from poke_env.data import GenData

# Engine Type enum order (must match cinnabar::Type, excluding None).
ORDER = ["NORMAL", "FIGHTING", "FLYING", "POISON", "GROUND", "ROCK", "BUG", "GHOST",
         "FIRE", "WATER", "GRASS", "ELECTRIC", "PSYCHIC", "ICE", "DRAGON"]
ENUM = {  # type name -> C++ Type:: literal
    t: "Type::" + t.capitalize() for t in ORDER
}

# Our current hand-coded chart, as (attacker, defender, x100) for non-neutral cells.
# Mirrors build_chart() in src/engine.cpp; everything else is 100 (neutral).
OURS_ENTRIES = [
    ("NORMAL", "ROCK", 50), ("NORMAL", "GHOST", 0),
    ("FIGHTING", "NORMAL", 200), ("FIGHTING", "ROCK", 200), ("FIGHTING", "ICE", 200),
    ("FIGHTING", "FLYING", 50), ("FIGHTING", "POISON", 50), ("FIGHTING", "BUG", 50),
    ("FIGHTING", "PSYCHIC", 50), ("FIGHTING", "GHOST", 0),
    ("FLYING", "FIGHTING", 200), ("FLYING", "BUG", 200), ("FLYING", "GRASS", 200),
    ("FLYING", "ROCK", 50), ("FLYING", "ELECTRIC", 50),
    ("POISON", "BUG", 200), ("POISON", "GRASS", 200), ("POISON", "POISON", 50),
    ("POISON", "GROUND", 50), ("POISON", "ROCK", 50), ("POISON", "GHOST", 50),
    ("GROUND", "POISON", 200), ("GROUND", "ROCK", 200), ("GROUND", "FIRE", 200),
    ("GROUND", "ELECTRIC", 200), ("GROUND", "GRASS", 50), ("GROUND", "BUG", 50),
    ("GROUND", "FLYING", 0),
    ("ROCK", "FLYING", 200), ("ROCK", "BUG", 200), ("ROCK", "FIRE", 200),
    ("ROCK", "ICE", 200), ("ROCK", "FIGHTING", 50), ("ROCK", "GROUND", 50),
    ("BUG", "POISON", 200), ("BUG", "GRASS", 200), ("BUG", "PSYCHIC", 200),
    ("BUG", "FIGHTING", 50), ("BUG", "FLYING", 50), ("BUG", "GHOST", 50), ("BUG", "FIRE", 50),
    ("GHOST", "GHOST", 200), ("GHOST", "NORMAL", 0), ("GHOST", "PSYCHIC", 0),
    ("FIRE", "BUG", 200), ("FIRE", "GRASS", 200), ("FIRE", "ICE", 200),
    ("FIRE", "ROCK", 50), ("FIRE", "FIRE", 50), ("FIRE", "WATER", 50), ("FIRE", "DRAGON", 50),
    ("WATER", "GROUND", 200), ("WATER", "ROCK", 200), ("WATER", "FIRE", 200),
    ("WATER", "WATER", 50), ("WATER", "GRASS", 50), ("WATER", "DRAGON", 50),
    ("GRASS", "GROUND", 200), ("GRASS", "ROCK", 200), ("GRASS", "WATER", 200),
    ("GRASS", "FLYING", 50), ("GRASS", "POISON", 50), ("GRASS", "BUG", 50),
    ("GRASS", "FIRE", 50), ("GRASS", "GRASS", 50), ("GRASS", "DRAGON", 50),
    ("ELECTRIC", "FLYING", 200), ("ELECTRIC", "WATER", 200), ("ELECTRIC", "GRASS", 50),
    ("ELECTRIC", "ELECTRIC", 50), ("ELECTRIC", "DRAGON", 50), ("ELECTRIC", "GROUND", 0),
    ("PSYCHIC", "FIGHTING", 200), ("PSYCHIC", "POISON", 200), ("PSYCHIC", "PSYCHIC", 50),
    ("ICE", "FLYING", 200), ("ICE", "GROUND", 200), ("ICE", "GRASS", 200),
    ("ICE", "DRAGON", 200), ("ICE", "WATER", 50), ("ICE", "ICE", 50),
    ("DRAGON", "DRAGON", 200),
]


def ours_matrix() -> dict[tuple[str, str], int]:
    m = {(a, d): 100 for a in ORDER for d in ORDER}
    for a, d, v in OURS_ENTRIES:
        m[(a, d)] = v
    return m


def correct_matrix(gen1: GenData) -> dict[tuple[str, str], int]:
    """Build the authoritative chart from poke-env's type_chart, orientation-agnostically."""
    raw = gen1.type_chart or gen1.load_type_chart(1)
    chart = {k.upper(): {a.upper(): float(v) for a, v in d.items()} for k, d in raw.items()}

    # poke-env's chart is keyed by defender; verify orientation with a known case.
    def defender_outer(atk, dfn):
        return chart.get(dfn, {}).get(atk, 1.0)

    if abs(defender_outer("WATER", "FIRE") - 2.0) > 1e-6:
        raise SystemExit(
            "Unexpected type_chart orientation/values; inspect gen1.type_chart manually.\n"
            f"sample FIRE entry: {chart.get('FIRE')}"
        )
    return {(a, d): round(defender_outer(a, d) * 100) for a in ORDER for d in ORDER}


def emit_header(correct: dict[tuple[str, str], int], dex: dict, out: Path) -> None:
    lines = [
        "// AUTO-GENERATED by engine/tools/gen_data.py from Showdown (poke-env) Gen 1 data.",
        "// Do not edit by hand; regenerate instead.",
        "#pragma once",
        '#include "cinnabar/engine.hpp"',
        "",
        "namespace cinnabar {",
        "",
        "// Type effectiveness x100, indexed [attacking][defending] in Type enum order.",
        "inline const int GEN1_TYPE_CHART[15][15] = {",
    ]
    for a in ORDER:
        row = ", ".join(f"{correct[(a, d)]:3d}" for d in ORDER)
        lines.append(f"    {{{row}}},  // {a}")
    lines.append("};")
    lines.append("")

    # Base stats (Gen 1: special = spa). Types mapped to the Type enum.
    lines.append("struct SpeciesEntry { const char* name; Type t1, t2; int hp, atk, def, spc, spe; };")
    lines.append("inline const SpeciesEntry GEN1_SPECIES[] = {")
    for key in sorted(dex, key=lambda k: dex[k].get("num", 0)):
        e = dex[key]
        bs = e.get("baseStats") or e.get("base_stats")
        types = [t.upper() for t in e.get("types", [])]
        if not bs or not types:
            continue
        t1 = ENUM[types[0]]
        t2 = ENUM[types[1]] if len(types) > 1 else "Type::None"
        name = e.get("name", key)
        lines.append(
            f'    {{"{name}", {t1}, {t2}, {bs["hp"]}, {bs["atk"]}, {bs["def"]}, {bs["spa"]}, {bs["spe"]}}},'
        )
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace cinnabar")
    out.write_text("\n".join(lines) + "\n")


def main() -> None:
    gen1 = GenData.from_gen(1)
    ours = ours_matrix()
    correct = correct_matrix(gen1)

    mismatches = [(a, d, ours[(a, d)], correct[(a, d)]) for a in ORDER for d in ORDER
                  if ours[(a, d)] != correct[(a, d)]]
    print(f"=== Type-chart audit (hand-coded vs Showdown gen 1) ===")
    if not mismatches:
        print("  no mismatches — hand-coded chart matches the oracle.")
    else:
        print(f"  {len(mismatches)} mismatch(es):")
        for a, d, o, c in mismatches:
            print(f"    {a:8s} -> {d:8s}: ours {o/100:>4} , correct {c/100:>4}")

    dex = gen1.pokedex or gen1.load_pokedex(1)
    out = Path(__file__).resolve().parents[1] / "include" / "cinnabar" / "gen1_data.hpp"
    emit_header(correct, dex, out)
    print(f"\nwrote {out} ({len(dex)} species + corrected type chart)")


if __name__ == "__main__":
    main()
